import * as stylex from '@stylexjs/stylex';

import { colors, radius } from './lib/tokens.stylex';

const mobile = '@media (max-width: 760px)';

export const styles = stylex.create({
	root: {
		backgroundColor: colors.background,
		color: colors.foreground,
		fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
		fontSynthesis: 'none',
		inset: 0,
		minWidth: '320px',
		overflow: 'auto',
		position: 'fixed',
	},
	app: { boxSizing: 'border-box', minHeight: '100%', width: '100%' },
	heading: {
		fontFamily: 'Georgia, serif',
		fontSize: 'clamp(2rem, 5vw, 4.2rem)',
		lineHeight: 0.95,
		marginTop: 0,
	},
	headingTwo: { fontSize: '1.1rem', marginTop: 0 },
	paragraph: { marginTop: 0 },
	link: { color: colors.link },
	eyebrow: {
		color: colors.eyebrow,
		fontSize: '0.73rem',
		fontWeight: 800,
		letterSpacing: '0.12em',
		marginBottom: '0.45rem',
		marginTop: 0,
	},
	lede: {
		color: colors.lede,
		fontSize: '1.15rem',
		lineHeight: 1.5,
		marginBottom: '1rem',
		marginTop: 0,
		maxWidth: '44rem',
	},
	finePrint: {
		color: colors.mutedForeground,
		fontSize: '0.85rem',
		marginTop: 0,
	},
	launch: {
		alignContent: 'center',
		backgroundColor: colors.background,
		backgroundImage: `radial-gradient(circle at 76% 20%, ${colors.launchGlow} 0, transparent 35%)`,
		display: 'grid',
		gap: '1.25rem',
		justifyItems: 'start',
		padding: 'clamp(2rem, 8vw, 8rem)',
	},
	launchAction: {
		minWidth: '240px',
		textAlign: 'center',
		textDecorationLine: 'none',
	},
	launchUtility: {
		alignItems: 'center',
		display: 'flex',
		justifyContent: 'space-between',
		width: 'min(44rem, 100%)',
	},
	savedGame: { gap: '0.75rem', width: 'min(28rem, 100%)' },
	appCard: { gap: '0.75rem', paddingInline: '1rem' },
	confirm: {
		alignItems: 'center',
		color: colors.confirm,
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.5rem',
	},
	setup: {
		margin: '0 auto',
		maxWidth: '1000px',
		padding: '2rem clamp(1rem, 4vw, 3rem)',
	},
	setupHeader: { marginBottom: '1.5rem' },
	setupUtility: {
		alignItems: 'center',
		display: 'flex',
		justifyContent: 'space-between',
	},
	setupHeading: { marginBottom: 0, marginTop: '0.65rem' },
	fieldLabel: {
		display: 'grid',
		fontWeight: 700,
		gap: '0.4rem',
		marginBottom: '1rem',
	},
	setupGrid: {
		display: 'grid',
		gap: '1rem',
		gridTemplateColumns: { default: 'repeat(3, 1fr)', [mobile]: '1fr' },
	},
	setupActions: {
		display: 'flex',
		flexDirection: { default: 'row', [mobile]: 'column' },
		gap: '0.75rem',
		marginBottom: '1rem',
		marginTop: '1rem',
	},
	setupAction: { width: { default: 'auto', [mobile]: '100%' } },
	reminders: { lineHeight: 1.5 },
	list: { marginTop: 0 },
	play: {
		backgroundColor: colors.playBackground,
		display: 'grid',
		gap: '12px',
		gridTemplateColumns: { default: '1.2fr 1fr 1fr', [mobile]: '1fr' },
		gridTemplateRows: { default: 'auto 1fr 1fr', [mobile]: 'none' },
		padding: '12px',
		paddingTop: '4rem',
	},
	dim: { filter: 'brightness(0.72)' },
	turnStrip: {
		alignItems: 'center',
		backgroundColor: colors.card,
		borderColor: colors.sidebarBorder,
		borderRadius: radius.lg,
		borderStyle: 'solid',
		borderWidth: '1px',
		display: 'grid',
		gap: '1rem',
		gridColumn: '1 / -1',
		gridTemplateColumns: { default: '1fr 1.5fr auto', [mobile]: '1fr' },
		padding: '0.75rem 1rem',
	},
	turnHeading: {
		fontFamily: 'Georgia, serif',
		fontSize: 'clamp(1.6rem, 3vw, 2.7rem)',
		lineHeight: 0.95,
		margin: 0,
	},
	playerPills: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.45rem',
		justifyContent: { default: 'center', [mobile]: 'flex-start' },
	},
	pill: {
		borderRadius: '100px',
		color: colors.primaryForeground,
		fontSize: '0.85rem',
		fontWeight: 800,
		opacity: 0.65,
		padding: '0.4rem 0.55rem',
	},
	activePill: { outline: `2px solid ${colors.activePillOutline}`, opacity: 1 },
	ember: { backgroundColor: '#e77a59' },
	cobalt: { backgroundColor: '#73afd7' },
	verdant: { backgroundColor: '#7fbd79' },
	gold: { backgroundColor: '#e4c35d' },
	turnControls: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.5rem',
		width: { default: 'auto', [mobile]: '100%' },
	},
	turnButton: { flexGrow: { default: 0, [mobile]: 1 } },
	turnAid: { gridRow: { default: '2 / 4', [mobile]: 'auto' } },
	scratchpad: {
		alignContent: 'start',
		display: 'grid',
		gap: '0.55rem',
		gridColumn: { default: '2', [mobile]: 'auto' },
		gridRow: { default: '2', [mobile]: 'auto' },
	},
	boxing: {
		alignContent: 'start',
		gridColumn: { default: '3', [mobile]: 'auto' },
		gridRow: { default: '2', [mobile]: 'auto' },
	},
	training: {
		gridColumn: { default: '2 / 4', [mobile]: 'auto' },
		gridRow: { default: '3', [mobile]: 'auto' },
		lineHeight: 1.4,
	},
	sectionHeading: {
		alignItems: 'flex-start',
		display: 'flex',
		gap: '0.75rem',
		justifyContent: 'space-between',
	},
	check: {
		alignItems: 'flex-start',
		borderTop: `1px solid ${colors.checkBorder}`,
		display: 'flex',
		gap: '0.65rem',
		lineHeight: 1.35,
		paddingBottom: '0.8rem',
		paddingTop: '0.8rem',
	},
	counter: {
		alignItems: 'center',
		display: 'grid',
		gap: '0.4rem',
		gridTemplateColumns: '1fr 44px 46px 44px',
	},
	counterOutput: { fontSize: '1.5rem', fontWeight: 800, textAlign: 'center' },
	spend: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '0.5rem',
		marginTop: '0.5rem',
	},
	spendLabel: {
		alignItems: 'center',
		display: 'flex',
		fontSize: '0.8rem',
		fontWeight: 700,
		gap: '0.4rem',
	},
	purchaseInput: { minHeight: '44px', padding: '0.3rem', width: '4.5rem' },
	muted: { color: colors.mutedForeground, fontSize: '0.85rem', marginTop: 0 },
	boxingTitle: { fontSize: '1.1rem', marginBottom: '0.15rem', marginTop: 0 },
	boxingRow: {
		alignItems: 'center',
		borderTop: `1px solid ${colors.checkBorder}`,
		display: 'grid',
		gap: '0.4rem',
		gridTemplateColumns: '28px 1fr 44px 46px 44px',
		paddingBottom: '0.5rem',
		paddingTop: '0.5rem',
	},
	marker: {
		borderRadius: '50%',
		color: colors.markerForeground,
		display: 'grid',
		fontSize: '0.75rem',
		height: '24px',
		placeItems: 'center',
		width: '24px',
	},
	trainingTrack: {
		display: 'grid',
		gap: '0.35rem',
		gridTemplateColumns: 'repeat(10, minmax(0, 1fr))',
		marginBottom: '0.75rem',
		marginTop: '0.75rem',
	},
	trackSpace: {
		borderColor: colors.trackBorder,
		borderRadius: radius.sm,
		borderStyle: 'solid',
		borderWidth: '1px',
		color: colors.trackForeground,
		display: 'grid',
		fontSize: '0.8rem',
		minHeight: '42px',
		placeItems: 'center',
	},
	reachedTrackSpace: {
		backgroundColor: colors.trackReached,
		borderColor: colors.trackReachedBorder,
		color: colors.trackReachedForeground,
	},
	currentTrackSpace: {
		backgroundColor: colors.primary,
		borderColor: colors.trackCurrentBorder,
		color: colors.primaryForeground,
		fontWeight: 800,
	},
	currentTrackLabel: { display: 'block', fontSize: '0.55rem' },
	endGameDialog: {
		backgroundColor: '#000a',
		display: 'grid',
		gap: '0.8rem',
		inset: 0,
		padding: '2rem',
		placeContent: 'center',
		position: 'fixed',
		textAlign: 'center',
		zIndex: 2,
	},
	dialogItem: { maxWidth: '28rem' },
	themeToggle: {
		alignItems: 'center',
		backgroundColor: { ':hover': colors.accent, default: 'transparent' },
		borderWidth: 0,
		borderRadius: radius.md,
		color: colors.foreground,
		cursor: 'pointer',
		display: 'inline-flex',
		fontSize: '0.8rem',
		fontWeight: 700,
		gap: '0.35rem',
		height: '2.25rem',
		paddingInline: '0.6rem',
		textTransform: 'capitalize',
	},
	themeToggleIcon: { height: '1rem', width: '1rem' },
});
